config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/activities/:activity_id/bookings/:id/checkout", to: "bookings#checkout", as: "checkout"
  resources :activities do
    resources :bookings, except: %i[index destroy]
  end

  resources :venues do
    resources :activities, only: :new
  end
  get 'all_activities', to: 'activities#all_activities'


  resources :bookings, only: %i[index destroy]

  get "my_venues", to: 'venues#my_venues'


  # Defines the root path route ("/")
  # root "articles#index"
end

# resources :activities do
#   resources :bookings, except: :index
# end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="mobile-nav">
      <div class="nav-labels">
        <%= link_to root_path, class:"bloc-icon" do %>
          <i class="bi bi-house-door"></i>
        <% end %>
        <p>Home</p>
      </div>
      <div class="nav-labels">
        <%= link_to bookings_path, class:"bloc-icon" do %>
          <i class="bi bi-book"></i>
        <% end %>
        <p>Bookings</p>
      </div>
      <div class="nav-labels">
        <%= link_to profile_path, class:"bloc-icon" do %>
            <i class="bi bi-person-circle"></i>
        <% end %>
        <p>Profile</p>
      </div>
</nav>

app/views/shared/_search.html.erb
<div class="search">
  <%= form_with url: activities_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-bar-home-form-control",
      placeholder: "Find a venue or activity"%>
      <%= submit_tag "Search", class: "btn btn-light", style:"display:none;" %>
    <% end %>
</div>

app/views/shared/_top_navbar.html.erb
<div class="top-navbar">
   <h1 class="logo " class><%= link_to "O&A", root_path %></h1>
   <% unless params[:controller] == "pages" && params[:action] == "home" %>
  <div class="search-top-bar">
    <%= form_with url: activities_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "nav-form-control",
        placeholder: "Search For Activities"%>
        <%= submit_tag "Search", class: "btn btn-light", style:"display:none;" %>
        <% end %>
      <% end %>
  </div>
</div>