config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/activities/:activity_id/bookings/:id/checkout", to: "bookings#checkout", as: "checkout"
  resources :activities do
    resources :bookings, except: %i[index destroy]
  end

  resources :venues do
    resources :activities, only: :new
  end
  get 'all_activities', to: 'activities#all_activities'


  resources :bookings, only: %i[index destroy]

  get "my_venues", to: 'venues#my_venues'


  # Defines the root path route ("/")
  # root "articles#index"
end

# resources :activities do
#   resources :bookings, except: :index
# end

app/views/pages/home.html.erb
<%= render "shared/search" %>
<div class="hero">
  <h1 class="logo-home"><%= link_to "O&A", root_path %></h1>
  <div class="hero-text">
    <% if user_signed_in? %>
      <h1 class="banner-slogan">Hello, <%= current_user.first_name %>!</h1>
    <% else %>
      <h1 class="banner-slogan">Out N' About</h1>
    <% end %>
    <p>Discover what the world has to offer</p>
  </div>
</div>
<div class="home-boxes">
  <div class="venue-box">
    <%= link_to all_activities_path do %>
      <i class="bi bi-people"></i>
    <% end %>
    <p class="box-text">Activities</p>
  </div>
  <div class="venue-box">
    <%= link_to venues_path do %>
      <i class="bi bi-pin-map"></i>
    <% end %>
    <p class="box-text">Venues</p>
  </div>
</div>

<div class="container home-cards-container">
  <h2 style="position: absolute;top: -30px;font-size: 22px;color: #383838;">Recently Added </h2>
  <div class="scrollmenu">
    <% @activities.order('created_at DESC').each do |a| %>
        <div class="card-new" onclick="this.querySelector('a').click(); return true;">
          <div class="before-line">
            <div class="name-image">
              <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>">
                <div class="home-card-top">
                  <h2><%= link_to a.name, activity_path(a.id), style:"text-decoration:none; color:white;"%></h2>
                  <h5><%= a.venue.name %></h5>
                </div>
            </div>
            <hr>
          </div>
          <div class="card-deets">
            <div class="deet">
              <p class="card-new-address">📍 <%= a.venue.address %></p>
            </div>
          </div>
          <div class="card-price">
            <p class="card-new-price">£<%= a.price %></p>
          </div>
        </div>
      <% end %>
  </div>


  <div class="bowling-scroll">
    <h2 style="position: absolute;top: -30px;font-size: 22px;color: #383838;">Bowling</h2>
    <div class="scrollmenu">
      <% @bowling.shuffle.each do |a| %>
        <div class="card-new" onclick="this.querySelector('a').click(); return true;">
          <div class="before-line">
            <div class="name-image">
              <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>">
                <div class="home-card-top">
                  <h2><%= link_to a.name, activity_path(a.id), style:"text-decoration:none; color:white;"%></h2>
                  <h5><%= a.venue.name %></h5>
                </div>
            </div>
            <hr>
          </div>
          <div class="card-deets">
            <div class="deet">
              <p class="card-new-address">📍 <%= a.venue.address %></p>
            </div>
          </div>
          <div class="card-price">
            <p class="card-new-price">£<%= a.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

    <div class="escape-scroll">
    <h2 style="position: absolute;top: -30px;font-size: 22px;color: #383838;">Escape Rooms</h2>
    <div class="scrollmenu">
      <% @escape.shuffle.each do |a| %>
        <div class="card-new" onclick="this.querySelector('a').click(); return true;">
          <div class="before-line">
            <div class="name-image">
              <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>">
                <div class="home-card-top">
                  <h2><%= link_to a.name, activity_path(a.id), style:"text-decoration:none; color:white;"%></h2>
                  <h5><%= a.venue.name %></h5>
                </div>
            </div>
            <hr>
          </div>
          <div class="card-deets">
            <div class="deet">
              <p class="card-new-address">📍 <%= a.venue.address %></p>
            </div>
          </div>
          <div class="card-price">
            <p class="card-new-price">£<%= a.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="profile-container">
  <% if user_signed_in? %>
    <div class="profile-top">
      <h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
      <h3><%= current_user.email %></h3>
      <p>Member since <%= current_user.created_at.strftime("%d-%m-%Y") %></p>
      <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-primary" %>
      <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class:"btn btn-secondary" %>
    </div>
    <hr>
    <div>
      <div class="profile-h1">
        <div style="display:flex; justify-content:space-between; width:100%;">
          <h3>My Venues</h3>
          <div>
            <%= link_to "Add Venue", new_venue_path, class:"btn btn-primary", style:"border-radius:5px;font-size: 10px;"%>
          </div>
        </div>
      </div>
      <% @venues.each do |v| %>
        <div class="card-trip" onclick="this.querySelector('a').click(); return true;">
          <img src="<%= v.photo.attached? ? (cl_image_path v.activities.first.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>" />
          <div class="card-trip-infos">
            <div>
              <h2><%= link_to v.name, venue_path(v.id) %></h2>
              <p><%= v.address %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="register-buttons">
      <%= link_to "Login", new_user_session_path, class:"btn btn-primary"  %>
      <br>
      <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-secondary" %>
    </div>
  <% end %>
</div>