config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/activities/:activity_id/bookings/:id/checkout", to: "bookings#checkout", as: "checkout"
  resources :activities do
    resources :bookings, except: %i[index destroy]
  end

  resources :venues do
    resources :activities, only: :new
  end
  get 'all_activities', to: 'activities#all_activities'


  resources :bookings, only: %i[index destroy]

  get "my_venues", to: 'venues#my_venues'


  # Defines the root path route ("/")
  # root "articles#index"
end

# resources :activities do
#   resources :bookings, except: :index
# end

app/models/venue.rb
class Venue < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  include PgSearch::Model
  multisearchable against: [:name]
  has_many :activities, dependent: :destroy
  has_many :slots, through: :activities, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true

  has_one_attached :photo


end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  def index
    @venues = Venue.all

    @markers = @venues.geocoded.map do |v|
      {
        lat: v.latitude,
        lng: v.longitude,
        info_window: render_to_string(partial: "info_window", locals: { v: v }),
        image_url: helpers.asset_url("pin.png")

      }
    end
  end

  def new
    @venue = Venue.new
    # @venue = Venue.where(current_user.id == :user_id)
  end

  def my_venues
    @venues = Venue.where(user: current_user)
  end

  def show
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def destroy
    @activity = Activity.where(venue: @venue)
    @activity.each { |a| a.destroy }
    @venue.destroy!
    redirect_to profile_path
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address, :description, :photo)
  end

  def set_venue
    @venue = Venue.find(params[:id])
  end
end

app/views/venues/_info_window.html.erb
<h2><%= v.name %></h2>
<p><%= v.address %></p>

app/views/venues/edit.html.erb
<div class="venue-new-container">
  <h3>Edit <%= @venue.name %></h3>
    <div class="new-venue-form">
      <%= simple_form_for @venue do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.button :submit, 'Edit Venue', class:"btn btn-primary" %>
      <% end %>
    </div>
</div>

app/views/venues/index.html.erb
<div class="venues-activities-index">
    <div class="index-head">
      <div class="my-venues-activities-headers">
        <h1 class="mt-4">Venues</h1>
        <div>
          <%= link_to "Add Venue", new_venue_path, class:"btn btn-primary mt-3", style:"border-radius:5px;"%>
        </div>
      </div>
      <hr>
    </div>
    <div class="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <% @venues.each do |v| %>
      <div class="card-trip" onclick="this.querySelector('a').click(); return true;">
        <img src="<%= v.photo.attached? ? (cl_image_path v.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>" />
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to v.name, venue_path(v.id), style:"text-decoration:none; color:black;" %></h2>
            <p><%= v.address %></p>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/venues/my_venues.html.erb
<div class="my-venue-container">
  <div class="my-venue-headers">
    <h1><strong>My Venues</strong></h1>
    <div>
      <%= link_to "Add Venue", new_venue_path, class:"btn btn-primary"%>
    </div>
  </div>
  <div class="my-v-cards">
    <% @venues.each do |v| %>
    <h5><%= link_to v.name, venue_path(v.id) %></h5>
    <h6><%= v.address %></h6>
    <p><%= v.description %></p>
    <% end %>
  </div>
</div>

app/views/venues/new.html.erb
<div class="venue-new-container">

  <h1><strong>New Venue</strong></h1>
  <div class="new-venue-form">
    <%= simple_form_for @venue do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.button :submit, 'Create Venue', class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/venues/show.html.erb
<div class="venue-show-container">
  <div class="show-page-headers">
    <div class="venue-show-cards">
      <h1><%= @venue.name %></h1>
      <hr>
      <p><%= @venue.description %></p>
      <hr>
      <h5><%= @venue.address %></h5>
    </div>
    <div class="venue-show-button">
      <% if @venue.user.id == current_user.id %>
        <%= link_to "Add Activity", new_venue_activity_path(@venue.id), class:"btn btn-primary" %>
        <%= link_to edit_venue_path(@venue.id) do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
        <%= link_to @venue, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="bi bi-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr>
  <h1>Activities at <%= @venue.name %></h1>
  <% @activity = Activity.where(venue: @venue.id) %>
    <% @activity.each do |a| %>
      <div class="card-trip" onclick="this.querySelector('a').click(); return true;">
        <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>" />
        <div class="card-trip-infos" >
          <div style="width:100%;">
            <div class="d-flex" style="justify-content:space-between;">
              <h2><%= link_to a.name, activity_path(a.id), style:"text-decoration:none; color:black;" %></h2>
              <h2>£<%= a.price %></h2>
            </div>
            <p><%= a.venue.name %></p>
          </div>
        </div>
      </div>
    <% end %>
</div>