config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'profile', to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/activities/:activity_id/bookings/:id/checkout", to: "bookings#checkout", as: "checkout"
  resources :activities do
    resources :bookings, except: %i[index destroy]
  end

  resources :venues do
    resources :activities, only: :new
  end
  get 'all_activities', to: 'activities#all_activities'


  resources :bookings, only: %i[index destroy]

  get "my_venues", to: 'venues#my_venues'


  # Defines the root path route ("/")
  # root "articles#index"
end

# resources :activities do
#   resources :bookings, except: :index
# end

app/models/activity.rb
class Activity < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name, :category]
  # CATEGORY = %w(bowling ping-pong darts go-karting rock-climbing trampolining mini-golf vr-gaming ice-skating escape-room)

  has_many :slots, dependent: :destroy

  belongs_to :venue

  validates :name, presence: true
  validates :description, presence: true
  validates :operational_start_time, presence: true
  validates :activity_party_size, presence: true
  validates :price, presence: true
  validates :operational_end_time, presence: true

  has_one_attached :photo

  def slot_time
    "#{@activity.slots.start_time.strftime("%R")} - #{@activity.slots.end_time.strftime("%R")}"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    # if params[:query].present? && !params[:query].empty?
    #   @activities = PgSearch.multisearch(params[:query])
    # elsif params[:query]
    #   @activities = Activity.all
    # else
    #   @activities = Activity.all
    # end

    # @activities_pg = PgSearch.multisearch(params[:query]).where(searchable_type: "Activity")
    # @activites = @activities_pg.map do |activity_pg|
    #   Activity.find(activity_pg.searchable_id)
    # end

    # @venues_pg = PgSearch.multisearch(params[:query]).where(searchable_type: "Venue")
    # @venues = @venues_pg.map! do |venue_pg|
    #   Venue.find(venue_pg.searchable_id)
    # end
    # case
    # when @activites.present?

    if params[:query].present?
      @activities = Activity.where("name ILIKE ?", "%#{params[:query]}%")
        if @activities.empty?
          @venues = Venue.where("name ILIKE ?", "%#{params[:query]}%")
        else
          @venues = []
          @activities.each do |activity|
            @venues << activity.venue
          end
        end
    end
  end

  def all_activities
    @activities = Activity.all
    if params[:query].present?
      if params[:query].present?
        sql_query = "category ILIKE :query or price ILIKE :query"
        @activities = Activity.where(sql_query, query: "%#{params[:query]}%")
      else
        @activities = Activity.all
      end
    else
      if params[:category] == "bowling"
        @activities = Activity.where(category: "bowling")
      end
      if params[:category] == "skating"
        @activities = Activity.where(category: "skating")
      end
      if params[:category] == "darts"
        @activities = Activity.where(category: "darts")
      end
      if params[:category] == "karting"
        @activities = Activity.where(category: "karting")
      end
      if params[:category] == "escape room"
        @activities = Activity.where(category: "escape room")
      end
      # if params[:price] == "escape room"
      #   @activities = Activity.where(category: "escape room")
      # end
    end
  end

  def new
    @venue = Venue.find(params[:venue_id])
    if current_user.nil?
      redirect_to new_user_session_path
      flash[:notice] = "Please Log In"
    else
      @activity = Activity.new
    end
  end

  def show
    @booking = Booking.new
    @slots_available = Slot.available.where(activity: @activity)
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.venue = Venue.find(params[:activity][:venue])
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @activity.update(activity_params)
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity.destroy!
    redirect_to all_activities_path
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :operational_start_time, :operational_end_time, :activity_party_size, :price, :category, :photo)
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end
end

app/views/activities/all_activities.html.erb
<div class="venues-activities-index">
  <div class="index-head">
    <div class="my-venues-activities-headers">
      <h1 class="mt-4">Activities</h1>
        <div class="filters">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to all_activities_path(category: "bowling") do %>
                  <p class= "filter <%= "selected" if params[:category]%>">Bowling</p>
                <% end %>
              </li>
              <li><%= link_to all_activities_path(category: "skating") do %>
                  <p class= "filter <%= "selected" if params[:category]%>">Skating</p>
                <% end %>
              </li>
              <li><%= link_to all_activities_path(category: "darts") do %>
                  <p class= "filter <%= "selected" if params[:category]%>">Darts</p>
                <% end %>
              </li>
              <li><%= link_to all_activities_path(category: "escape room") do %>
                  <p class= "filter <%= "selected" if params[:category]%>">Escape Rooms</p>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
    </div>
    <hr>
  </div>
    <ul>
    <% @activities.each do |a| %>
      <div class="card-trip" onclick="this.querySelector('a').click(); return true;">
        <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>" />
        <div class="card-trip-infos" >
          <div style="width:100%;">
            <div class="d-flex" style="justify-content:space-between;">
              <h2><%= link_to a.name, activity_path(a.id), style:"text-decoration:none; color:black;" %></h2>
              <h2>£<%= a.price %></h2>
            </div>
            <p><%= a.venue.name %></p>
          </div>
        </div>
      </div>

    <% end %>
    </div>
  </div>

app/views/activities/edit.html.erb
<div class="form mt-4" style="width:90vw;margin:0 auto;">
  <h3>Edit Activity</h3>
  <div class="container">
    <div style="color:#362d77">
      <%= simple_form_for (@activity) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :operational_start_time %>
        <%= f.input :operational_end_time %>
        <%= f.input :activity_party_size %>
        <%= f.input :price %>
        <%= f.input :category %>
        <%# <%= f.input :photo, as: :file %>
        <%= f.submit class:"btn btn-primary"  %>
      <% end %>
    <br>
    </div>
    <%= link_to "Back", activity_path(@activity), class: "btn btn-secondary"   %>
  </div>
</div>

app/views/activities/index.html.erb
<br>
<div class="search-result-container container">

  <% if params[:query].present? %>
    <div class="venues-activities-index">
      <% @activities.each do |a| %>
        <div class="card-trip" onclick="this.querySelector('a').click(); return true;">
          <img src="<%= a.photo.attached? ? (cl_image_path a.photo.key) : 'https://m.media-amazon.com/images/S/aplus-media/vc/cab6b08a-dd8f-4534-b845-e33489e91240._CR75,0,300,300_PT0_SX300__.jpg'%>" />
          <div class="card-trip-infos">
            <div>
              <h2><%= link_to a.name, activity_path(a.id) %></h2>
              <p><%= a.venue.name %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/activities/new.html.erb
<div class="form mt-4" style="width:90vw;margin:0 auto;">
    <h1><strong>New Activity</strong></h1>
  <div class="container">
    <div style="color:#362d77">
      <%= simple_form_for (@activity), html: { class: "form-new-activity" } do |f| %>
        <%= f.input :venue, :as => :hidden, :input_html => { :value => @venue.id } %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :operational_start_time %>
        <%= f.input :operational_end_time %>
        <%= f.input :photo, as: :file %>
        <%= f.input :price %>
        <%= f.input :activity_party_size %>
        <%= f.input :category %>
        <%= f.button :submit, 'Create', class:"btn btn-primary"  %>
      <% end %>
    </div>
    <br>
    <%= link_to "Back", activities_path(@activity), class: "btn btn-outline-dark"%>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container activity-show-container">
  <div class="show-activities">
    <h1><strong><%= @activity.name.capitalize %></strong> at <%= @activity.venue.name %></h1>
      <div class="activity-show-margin">
        <h5><%= @activity.venue.address %> (<%= @activity.operational_start_time.strftime("%I:%M%p")%> - <%= @activity.operational_end_time.strftime("%I:%M%p") %>)</h5>
        <h4> £<%= @activity.price %>/person</h4>
        <br>
          <div class="activity-show-image">
            <% if @activity.photo.present? %>
            <%= cl_image_tag @activity.photo.key, crop: :fill %>
            <% end %>
          </div>
        <h5>Description</h5>
        <p><%= @activity.description %></p>
        <br>
        <h5>About <%= @activity.venue.name %></h5>
        <p><%= @activity.venue.description %></p>
      </div>
      <div>


        <% if current_user && current_user == @activity.venue.user %>
          <div class= "flex-container">
            <%= link_to "Back", root_path, class: "btn btn-link" %>
            <div class=activity-buttons>
              <%= link_to edit_activity_path(@activity.id) do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
              <%= link_to @activity, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="bi bi-trash"></i>
              <% end %>
            </div>
          </div>
          <% else %>
            <div class="back-button">
          <%= link_to "Back", root_path, class: "btn btn-link actual-button" %>
        </div>
        <% end %>
    </div>
  </div>

  <% if current_user != @activity.venue.user %>
    <div class="container-form-booking">
      <%= simple_form_for [@activity, @booking] do |f| %>
      <%= f.input :activity_date, as: :string, input_html: {type: :date}%>
      <%= f.association :slot, label: 'Please choose a time slot', label_method: :slot_time, value_method: :id, collection: @slots_available  %>
      <%# <% f.input :activity, as => :hidden, :input_html => { :value => @activity.current_user.slots.pluck(:activity_id).uniq} %>
      <%= f.input :user_party_size, label: 'Please choose a party size', as: :integer %>
      <%= f.button :submit, 'Book', class:"btn btn-light book-button" %>
      <% end %>
      <% end %>
  </div>
</div>